[tool.poetry]
name = "olive_exercises"
version = "0.1.0"
description = ""
authors = ["Zheng Hao Tan <hi@zhenghaotan.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
